Sample images and reports from `raw/` into a train-valid-test split, ready for the data loader.


In [11]:
import pandas as pd
from brainclip.config import *

parsed_reports_df = pd.read_csv(parsed_reports)
parsed_reports_df

Unnamed: 0             Dataset  \
0          720  IN-BodyScanData-03   
1          256  IN-BodyScanData-03   
2          822  IN-BodyScanData-03   
3         1030  IN-BodyScanData-03   
4          800  IN-BodyScanData-03   
5          610  IN-BodyScanData-03   
6          815  IN-BodyScanData-03   
7          796  IN-BodyScanData-03   
8          860  IN-BodyScanData-03   
9          524  IN-BodyScanData-03   
10         471  IN-BodyScanData-03   
11         334  IN-BodyScanData-03   
12        1069  IN-BodyScanData-03   
13          83  IN-BodyScanData-03   
14         884  IN-BodyScanData-03   
15         286  IN-BodyScanData-03   
16         328  IN-BodyScanData-03   
17         321  IN-BodyScanData-03   
18         579  IN-BodyScanData-03   
19         278  IN-BodyScanData-03   
20         423  IN-BodyScanData-03   
21         104  IN-BodyScanData-03   
22         130  IN-BodyScanData-03   
23         191  IN-BodyScanData-03   
24         548  IN-BodyScanData-03   
25         691  IN-BodyScanData-03   
26         906  IN-BodyScanData-03   
27          18  IN-BodyScanData-03   
28        1094  IN-BodyScanData-03   
29         510  IN-BodyScanData-03   
30          58  IN-BodyScanData-03   
31         134  IN-BodyScanData-03   
32         635  IN-BodyScanData-03   
33         698  IN-BodyScanData-03   
34        1047  IN-BodyScanData-03   
35         426  IN-BodyScanData-03   
36         180  IN-BodyScanData-03   
37           3  IN-BodyScanData-03   
38         323  IN-BodyScanData-03   
39          23  IN-BodyScanData-03   
40         140  IN-BodyScanData-03   
41         867  IN-BodyScanData-03   
42         262  IN-BodyScanData-03   
43         912  IN-BodyScanData-03   
44         505  IN-BodyScanData-03   
45         474  IN-BodyScanData-03   
46         277  IN-BodyScanData-03   
47        1020  IN-BodyScanData-03   
48         828  IN-BodyScanData-03   
49          87  IN-BodyScanData-03   

                                     StudyInstanceUID  \
0   1.2.826.1.3680043.9.5282.150415.40716.11040716...   
1   1.2.826.1.3680043.9.5282.150415.43774.11043774...   
2   1.2.826.1.3680043.9.5282.150415.26309.80263092...   
3   1.2.826.1.3680043.9.5282.150415.27625.80276252...   
4   1.2.826.1.3680043.9.5282.150415.23406.80234062...   
5   1.2.826.1.3680043.9.5282.150415.26626.80266262...   
6   1.2.826.1.3680043.9.5282.150415.16379.11016379...   
7   1.2.826.1.3680043.9.5282.150415.39304.11039304...   
8   1.2.826.1.3680043.9.5282.150415.42976.11042976...   
9   1.2.826.1.3680043.9.5282.150415.38559.80385592...   
10  1.2.826.1.3680043.9.5282.150415.39930.11039930...   
11  1.2.826.1.3680043.9.5282.150415.12543.11012543...   
12  1.2.826.1.3680043.9.5282.150415.18194.80181942...   
13  1.2.826.1.3680043.9.5282.150415.9683.110096832...   
14  1.2.826.1.3680043.9.5282.150415.27195.80271952...   
15  1.2.826.1.3680043.9.5282.150415.5508.110055082...   
16  1.2.826.1.3680043.9.5282.150415.59871.11059871...   
17  1.2.826.1.3680043.9.5282.150415.12681.11012681...   
18  1.2.826.1.3680043.9.5282.150415.18971.80189712...   
19  1.2.826.1.3680043.9.5282.150415.4344.110043442...   
20  1.2.826.1.3680043.9.5282.150415.30701.11030701...   
21  1.2.826.1.3680043.9.5282.150415.15401.80154012...   
22  1.2.826.1.3680043.9.5282.150415.7505.110075052...   
23  1.2.826.1.3680043.9.5282.150415.11331.11011331...   
24  1.2.826.1.3680043.9.5282.150415.35043.80350432...   
25  1.2.826.1.3680043.9.5282.150415.19726.80197262...   
26  1.2.826.1.3680043.9.5282.150415.45199.11045199...   
27  1.2.826.1.3680043.9.5282.150415.59056.11059056...   
28  1.3.12.2.1107.5.2.40.39004.3000002205230715593...   
29  1.2.826.1.3680043.9.5282.150415.25279.80252792...   
30  1.2.826.1.3680043.9.5282.150415.56354.11056354...   
31  1.2.826.1.3680043.9.5282.150415.55975.11055975...   
32  1.2.826.1.3680043.9.5282.150415.37450.11037450...   
33  1.2.826.1.3680043.9.5282.150415.36497.11036497...   
34  1.2.826.1.3680043.9.5282.150415.15984.11015984...   
35  1.2.826.1

In [2]:
#infarct_only = parsed_reports_df.copy()
#infarct_only = infarct_only.replace({"tumor":"others","hemorrhage":"others"})


In [14]:
from sklearn.model_selection import train_test_split

X, y = parsed_reports_df[["StudyInstanceUID","ParsedImpressions"]], parsed_reports_df["class"]
X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y, test_size=0.1, random_state=42)
X_train, X_valid, y_train, y_valid = train_test_split(X_train, y_train, stratify=y_train, test_size=0.1, random_state=42)

# do one split only (train, valid)

X_valid =pd.concat([X_valid,X_test])
y_valid = pd.concat([y_valid,y_test])

In [15]:
import numpy as np

len(y_train), np.unique(y_train, return_counts=True), np.unique(y_valid, return_counts=True), np.unique(y_test, return_counts=True)

(40,
 (array(['hemorrhage', 'infarct', 'normal', 'others', 'tumor'], dtype=object),
  array([8, 8, 8, 8, 8])),
 (array(['hemorrhage', 'infarct', 'normal', 'others', 'tumor'], dtype=object),
  array([2, 2, 2, 2, 2])),
 (array(['hemorrhage', 'infarct', 'normal', 'others', 'tumor'], dtype=object),
  array([1, 1, 1, 1, 1])))

In [16]:
y_test, y_valid

(43        normal
 2        infarct
 25    hemorrhage
 38        others
 49         tumor
 Name: class, dtype: object,
 19    hemorrhage
 17         tumor
 47        normal
 5        infarct
 31        others
 43        normal
 2        infarct
 25    hemorrhage
 38        others
 49         tumor
 Name: class, dtype: object)

In [17]:
import os
import json
import shutil
from brainclip.model.utils.processing import preprocess_image

sequences = ["DWI_B1000_0.nii.gz", "T2_FLAIR_0.nii.gz", "T2S_0.nii.gz"]
sequences = sequences[0]
access_dir = lambda filename: os.path.join(raw_images, filename, "Nifti")

moved_images = []
all_images = list(os.listdir("/datadrive_m2/alice/brain-CLIP/data/raw/images/Alice_IN-BodyScanData-03"))

def move_images_and_text(X, y, target_folder):
    data_dict = {}

    for n, (idx, row) in enumerate(X.iterrows()):
        img_name, txt  = row["StudyInstanceUID"], row["ParsedImpressions"]
        patient_folder = access_dir(img_name)        

        try: 
            for seq in os.listdir(patient_folder): # Modify this to add more sequences
                if sequences in seq:
                    img_path = os.path.join(patient_folder, seq)
                    target_path = os.path.join(data_folder, target_folder, f"image_{idx}.nii.gz")
                    # move image to target directory
                    shutil.copy(img_path, target_path)

                    preprocess_image(target_path)

                    # append label
                    data_dict[n] = {
                        "name":target_path, 
                        "report":txt, 
                        "label":y.loc[idx]
                    }

        except FileNotFoundError: 
            print(f"{target_folder}: Couldn't find {patient_folder}, {img_name}")
            display(X[X["StudyInstanceUID"] == img_name])

    with open(f"{data_folder}{target_folder}.json", "w") as f:json.dump(data_dict, f)
        

In [18]:
move_images_and_text(X_train, y_train, "train")
move_images_and_text(X_valid, y_valid, "valid")
#move_images_and_text(X_test, y_test, "test")